apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "try-runtime.fullname" . }}
  labels:
    {{- include "try-runtime.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "try-runtime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      # NOTE: Those annotations are needed so that GKE can update the
      # containers even when the image tag doesn't change between deployments
      # (e.g. on pushes)
      annotations:
        {{- include "try-runtime.labels" . | nindent 8 }}
      labels:
        {{- include "try-runtime.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "try-runtime.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: ping
              containerPort: {{ .Values.env.PING_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.env.PING_PORT }}
            failureThreshold: 0
            periodSeconds: 128
            initialDelaySeconds: 128
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.env.PING_PORT }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
              {{- if .Values.persistence.subPath }}
              subPath: "{{ .Values.persistence.subPath }}"
              {{- end }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
        {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "try-runtime.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
